### PR TITLE
Added attribution

### PR DESCRIPTION
**Pull request by KevinMulhern**
Added attribution to the odin project, the original creators of this content.

### CODE REVIEW

**Comment by Freika** [comment]
@KevinMulhern thanks for PR! It's already stated on 'About project' page on site, do you think this is necessary here?

**Comment by KevinMulhern** [comment]
Hey @Freika, yeah I think it's good practice to give credit in the README.

**Comment by Freika** [comment]
@KevinMulhern ok, why not :) I'll edit your text to make it more readable

**Comment by KevinMulhern** [comment]
haha thank you (I used google translate 😬) I really like the frontend you guys built for this. We could learn a thing or two from it.

**Comment by Freika** [comment]
Thanks :) Text updated.

**Pull request merged**
